spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weatherdb
    username: weatherdb
    password: password
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      idle-timeout: 30000
      pool-name: weather-api-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
